/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: "privacy" | "terms" | "cookies";
  title?: LocalizedText;
  lastUpdated?: string;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  bodyRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  seo?: SeoMetadata;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: LocalizedText;
  answer?: LocalizedText;
  group?: string;
};

export type BlogCategory = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  description?: LocalizedText;
  seo?: SeoMetadata;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  client?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  publishedAt?: string;
  services?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  heroImage?: MediaAsset;
  summary?: LocalizedText;
  atAGlance?: Array<{
    label?: LocalizedText;
    value?: LocalizedText;
    _key: string;
  }>;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  bodyRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  keyDecisions?: Array<{
    heading?: LocalizedText;
    rationale?: LocalizedText;
    _key: string;
  }>;
  outcomes?: Array<{
    metric?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  founderNote?: LocalizedText;
  relatedServices?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  nextCaseStudy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  };
  finalCta?: CtaBlock;
  seo?: SeoMetadata;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  order?: number;
  tagline?: LocalizedText;
  positioning?: LocalizedText;
  whoItsFor?: Array<
    {
      _key: string;
    } & LocalizedText
  >;
  whatsIncluded?: Array<
    {
      _key: string;
    } & LocalizedText
  >;
  processSteps?: Array<{
    heading?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  deliverables?: Array<
    {
      _key: string;
    } & LocalizedText
  >;
  techStack?: Array<string>;
  caseStudies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  }>;
  relatedServices?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  faq?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "faqItem";
  }>;
  finalCta?: CtaBlock;
  seo?: SeoMetadata;
};

export type ThankYouPage = {
  _id: string;
  _type: "thankYouPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: LocalizedText;
  message?: LocalizedText;
  nextSteps?: Array<{
    label?: LocalizedText;
    href?: string;
    _key: string;
  }>;
  seo?: SeoMetadata;
};

export type BlogIndexPage = {
  _id: string;
  _type: "blogIndexPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: LocalizedText;
  heroLead?: LocalizedText;
  featuredPost?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogPost";
  };
  seo?: SeoMetadata;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  publishedAt?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogCategory";
  }>;
  coverImage?: MediaAsset;
  excerpt?: LocalizedText;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  bodyRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  seo?: SeoMetadata;
};

export type WorkIndexPage = {
  _id: string;
  _type: "workIndexPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: LocalizedText;
  heroLead?: LocalizedText;
  featuredCaseStudies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  }>;
  seo?: SeoMetadata;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: LocalizedText;
  heroLead?: LocalizedText;
  contactMethods?: Array<{
    label?: LocalizedText;
    value?: string;
    href?: string;
    _key: string;
  }>;
  whatHappensNext?: Array<{
    heading?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  founderTrustSignal?: LocalizedText;
  faq?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "faqItem";
  }>;
  seo?: SeoMetadata;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroStatement?: LocalizedText;
  founder?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  whatItIsEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  whatItIsRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  howWeWorkEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  howWeWorkRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  principles?: Array<{
    heading?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  expertiseAreas?: Array<
    {
      _key: string;
    } & LocalizedText
  >;
  teamSummary?: LocalizedText;
  finalCta?: CtaBlock;
  seo?: SeoMetadata;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: LocalizedText;
  bio?: LocalizedText;
  photo?: MediaAsset;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: LocalizedText;
  heroLead?: LocalizedText;
  heroCta?: CtaBlock;
  positioningStatement?: LocalizedText;
  selectedWork?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  }>;
  servicesOverviewIntro?: LocalizedText;
  founderMomentHeading?: LocalizedText;
  founderMomentText?: LocalizedText;
  approachItems?: Array<{
    heading?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  finalCta?: CtaBlock;
  seo?: SeoMetadata;
};

export type GlobalSettings = {
  _id: string;
  _type: "globalSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  tagline?: LocalizedText;
  primaryEmail?: string;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  defaultSeo?: SeoMetadata;
};

export type CtaBlock = {
  _type: "ctaBlock";
  label?: LocalizedText;
  href?: string;
  variant?: "primary" | "ghost";
};

export type SeoMetadata = {
  _type: "seoMetadata";
  title?: LocalizedText;
  description?: LocalizedText;
  ogImage?: MediaAsset;
  noIndex?: boolean;
};

export type MediaAsset = {
  _type: "mediaAsset";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: LocalizedText;
  caption?: LocalizedText;
};

export type LocalizedText = {
  _type: "localizedText";
  en?: string;
  ru?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | LegalPage
  | FaqItem
  | BlogCategory
  | CaseStudy
  | Service
  | ThankYouPage
  | BlogIndexPage
  | BlogPost
  | WorkIndexPage
  | ContactPage
  | AboutPage
  | Author
  | HomePage
  | GlobalSettings
  | CtaBlock
  | SeoMetadata
  | MediaAsset
  | LocalizedText
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: lib/sanity/queries.ts
// Variable: globalSettingsQuery
// Query: *[_type == "globalSettings"][0]
export type GlobalSettingsQueryResult = {
  _id: string;
  _type: "globalSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  tagline?: LocalizedText;
  primaryEmail?: string;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  defaultSeo?: SeoMetadata;
} | null;
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]
export type HomePageQueryResult = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: LocalizedText;
  heroLead?: LocalizedText;
  heroCta?: CtaBlock;
  positioningStatement?: LocalizedText;
  selectedWork?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  }>;
  servicesOverviewIntro?: LocalizedText;
  founderMomentHeading?: LocalizedText;
  founderMomentText?: LocalizedText;
  approachItems?: Array<{
    heading?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  finalCta?: CtaBlock;
  seo?: SeoMetadata;
} | null;
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]
export type AboutPageQueryResult = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroStatement?: LocalizedText;
  founder?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  whatItIsEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  whatItIsRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  howWeWorkEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  howWeWorkRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  principles?: Array<{
    heading?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  expertiseAreas?: Array<
    {
      _key: string;
    } & LocalizedText
  >;
  teamSummary?: LocalizedText;
  finalCta?: CtaBlock;
  seo?: SeoMetadata;
} | null;
// Variable: contactPageQuery
// Query: *[_type == "contactPage"][0]
export type ContactPageQueryResult = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: LocalizedText;
  heroLead?: LocalizedText;
  contactMethods?: Array<{
    label?: LocalizedText;
    value?: string;
    href?: string;
    _key: string;
  }>;
  whatHappensNext?: Array<{
    heading?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  founderTrustSignal?: LocalizedText;
  faq?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "faqItem";
  }>;
  seo?: SeoMetadata;
} | null;
// Variable: workIndexPageQuery
// Query: *[_type == "workIndexPage"][0]
export type WorkIndexPageQueryResult = {
  _id: string;
  _type: "workIndexPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: LocalizedText;
  heroLead?: LocalizedText;
  featuredCaseStudies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  }>;
  seo?: SeoMetadata;
} | null;
// Variable: blogIndexPageQuery
// Query: *[_type == "blogIndexPage"][0]
export type BlogIndexPageQueryResult = {
  _id: string;
  _type: "blogIndexPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: LocalizedText;
  heroLead?: LocalizedText;
  featuredPost?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogPost";
  };
  seo?: SeoMetadata;
} | null;
// Variable: thankYouPageQuery
// Query: *[_type == "thankYouPage"][0]
export type ThankYouPageQueryResult = {
  _id: string;
  _type: "thankYouPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: LocalizedText;
  message?: LocalizedText;
  nextSteps?: Array<{
    label?: LocalizedText;
    href?: string;
    _key: string;
  }>;
  seo?: SeoMetadata;
} | null;
// Variable: serviceBySlugQuery
// Query: *[_type == "service" && (    ($locale == "en" && slugEn.current == $slug) ||    ($locale == "ru" && slugRu.current == $slug)  )][0]
export type ServiceBySlugQueryResult = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  order?: number;
  tagline?: LocalizedText;
  positioning?: LocalizedText;
  whoItsFor?: Array<
    {
      _key: string;
    } & LocalizedText
  >;
  whatsIncluded?: Array<
    {
      _key: string;
    } & LocalizedText
  >;
  processSteps?: Array<{
    heading?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  deliverables?: Array<
    {
      _key: string;
    } & LocalizedText
  >;
  techStack?: Array<string>;
  caseStudies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  }>;
  relatedServices?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  faq?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "faqItem";
  }>;
  finalCta?: CtaBlock;
  seo?: SeoMetadata;
} | null;
// Variable: allServicesQuery
// Query: *[_type == "service"] | order(order asc) {    _id,    "slugEn": slugEn.current,    "slugRu": slugRu.current,    title,    order  }
export type AllServicesQueryResult = Array<{
  _id: string;
  slugEn: string | null;
  slugRu: string | null;
  title: LocalizedText | null;
  order: number | null;
}>;
// Variable: caseStudyBySlugQuery
// Query: *[_type == "caseStudy" && (    ($locale == "en" && slugEn.current == $slug) ||    ($locale == "ru" && slugRu.current == $slug)  )][0]
export type CaseStudyBySlugQueryResult = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  client?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  publishedAt?: string;
  services?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  heroImage?: MediaAsset;
  summary?: LocalizedText;
  atAGlance?: Array<{
    label?: LocalizedText;
    value?: LocalizedText;
    _key: string;
  }>;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  bodyRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  keyDecisions?: Array<{
    heading?: LocalizedText;
    rationale?: LocalizedText;
    _key: string;
  }>;
  outcomes?: Array<{
    metric?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  founderNote?: LocalizedText;
  relatedServices?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  nextCaseStudy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  };
  finalCta?: CtaBlock;
  seo?: SeoMetadata;
} | null;
// Variable: allCaseStudySlugsQuery
// Query: *[_type == "caseStudy" && defined(slugEn.current) && defined(slugRu.current)] {    "slugEn": slugEn.current,    "slugRu": slugRu.current  }
export type AllCaseStudySlugsQueryResult = Array<{
  slugEn: string | null;
  slugRu: string | null;
}>;
// Variable: latestCaseStudiesQuery
// Query: *[_type == "caseStudy"] | order(publishedAt desc) [0...$limit]
export type LatestCaseStudiesQueryResult = Array<{
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  client?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  publishedAt?: string;
  services?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  heroImage?: MediaAsset;
  summary?: LocalizedText;
  atAGlance?: Array<{
    label?: LocalizedText;
    value?: LocalizedText;
    _key: string;
  }>;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  bodyRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  keyDecisions?: Array<{
    heading?: LocalizedText;
    rationale?: LocalizedText;
    _key: string;
  }>;
  outcomes?: Array<{
    metric?: LocalizedText;
    description?: LocalizedText;
    _key: string;
  }>;
  founderNote?: LocalizedText;
  relatedServices?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  nextCaseStudy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  };
  finalCta?: CtaBlock;
  seo?: SeoMetadata;
}>;
// Variable: blogPostBySlugQuery
// Query: *[_type == "blogPost" && (    ($locale == "en" && slugEn.current == $slug) ||    ($locale == "ru" && slugRu.current == $slug)  )][0]
export type BlogPostBySlugQueryResult = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  publishedAt?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogCategory";
  }>;
  coverImage?: MediaAsset;
  excerpt?: LocalizedText;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  bodyRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  seo?: SeoMetadata;
} | null;
// Variable: allBlogPostSlugsQuery
// Query: *[_type == "blogPost" && defined(slugEn.current) && defined(slugRu.current)] {    "slugEn": slugEn.current,    "slugRu": slugRu.current  }
export type AllBlogPostSlugsQueryResult = Array<{
  slugEn: string | null;
  slugRu: string | null;
}>;
// Variable: latestBlogPostsQuery
// Query: *[_type == "blogPost"] | order(publishedAt desc) [0...$limit]
export type LatestBlogPostsQueryResult = Array<{
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  publishedAt?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogCategory";
  }>;
  coverImage?: MediaAsset;
  excerpt?: LocalizedText;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  bodyRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  seo?: SeoMetadata;
}>;
// Variable: blogPostsByCategoryQuery
// Query: *[_type == "blogPost" && $categoryId in categories[]._ref] | order(publishedAt desc)
export type BlogPostsByCategoryQueryResult = Array<{
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  publishedAt?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogCategory";
  }>;
  coverImage?: MediaAsset;
  excerpt?: LocalizedText;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  bodyRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  seo?: SeoMetadata;
}>;
// Variable: allBlogCategorySlugsQuery
// Query: *[_type == "blogCategory" && defined(slugEn.current) && defined(slugRu.current)] {    "slugEn": slugEn.current,    "slugRu": slugRu.current  }
export type AllBlogCategorySlugsQueryResult = Array<{
  slugEn: string | null;
  slugRu: string | null;
}>;
// Variable: blogCategoryBySlugQuery
// Query: *[_type == "blogCategory" && (    ($locale == "en" && slugEn.current == $slug) ||    ($locale == "ru" && slugRu.current == $slug)  )][0]
export type BlogCategoryBySlugQueryResult = {
  _id: string;
  _type: "blogCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedText;
  slugEn?: Slug;
  slugRu?: Slug;
  description?: LocalizedText;
  seo?: SeoMetadata;
} | null;
// Variable: legalPageBySlugQuery
// Query: *[_type == "legalPage" && slug == $slug][0]
export type LegalPageBySlugQueryResult = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: "cookies" | "privacy" | "terms";
  title?: LocalizedText;
  lastUpdated?: string;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  bodyRu?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: LocalizedText;
        caption?: LocalizedText;
        _type: "image";
        _key: string;
      }
  >;
  seo?: SeoMetadata;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "globalSettings"][0]': GlobalSettingsQueryResult;
    '*[_type == "homePage"][0]': HomePageQueryResult;
    '*[_type == "aboutPage"][0]': AboutPageQueryResult;
    '*[_type == "contactPage"][0]': ContactPageQueryResult;
    '*[_type == "workIndexPage"][0]': WorkIndexPageQueryResult;
    '*[_type == "blogIndexPage"][0]': BlogIndexPageQueryResult;
    '*[_type == "thankYouPage"][0]': ThankYouPageQueryResult;
    '\n  *[_type == "service" && (\n    ($locale == "en" && slugEn.current == $slug) ||\n    ($locale == "ru" && slugRu.current == $slug)\n  )][0]\n': ServiceBySlugQueryResult;
    '\n  *[_type == "service"] | order(order asc) {\n    _id,\n    "slugEn": slugEn.current,\n    "slugRu": slugRu.current,\n    title,\n    order\n  }\n': AllServicesQueryResult;
    '\n  *[_type == "caseStudy" && (\n    ($locale == "en" && slugEn.current == $slug) ||\n    ($locale == "ru" && slugRu.current == $slug)\n  )][0]\n': CaseStudyBySlugQueryResult;
    '\n  *[_type == "caseStudy" && defined(slugEn.current) && defined(slugRu.current)] {\n    "slugEn": slugEn.current,\n    "slugRu": slugRu.current\n  }\n': AllCaseStudySlugsQueryResult;
    '\n  *[_type == "caseStudy"] | order(publishedAt desc) [0...$limit]\n': LatestCaseStudiesQueryResult;
    '\n  *[_type == "blogPost" && (\n    ($locale == "en" && slugEn.current == $slug) ||\n    ($locale == "ru" && slugRu.current == $slug)\n  )][0]\n': BlogPostBySlugQueryResult;
    '\n  *[_type == "blogPost" && defined(slugEn.current) && defined(slugRu.current)] {\n    "slugEn": slugEn.current,\n    "slugRu": slugRu.current\n  }\n': AllBlogPostSlugsQueryResult;
    '\n  *[_type == "blogPost"] | order(publishedAt desc) [0...$limit]\n': LatestBlogPostsQueryResult;
    '\n  *[_type == "blogPost" && $categoryId in categories[]._ref] | order(publishedAt desc)\n': BlogPostsByCategoryQueryResult;
    '\n  *[_type == "blogCategory" && defined(slugEn.current) && defined(slugRu.current)] {\n    "slugEn": slugEn.current,\n    "slugRu": slugRu.current\n  }\n': AllBlogCategorySlugsQueryResult;
    '\n  *[_type == "blogCategory" && (\n    ($locale == "en" && slugEn.current == $slug) ||\n    ($locale == "ru" && slugRu.current == $slug)\n  )][0]\n': BlogCategoryBySlugQueryResult;
    '\n  *[_type == "legalPage" && slug == $slug][0]\n': LegalPageBySlugQueryResult;
  }
}
