import type { QueryParams } from "next-sanity";
import { sanityClient } from "./client";

/**
 * Typed GROQ fetch. The query is kept as a literal string type (`const Q extends string`)
 * so the module augmentation generated by Sanity typegen can look it up in `SanityQueries`
 * and return the right result type automatically.
 *
 * Usage:
 *   import { sanityFetch } from "@/lib/sanity/fetch";
 *   import { homePageQuery } from "@/lib/sanity/queries";
 *
 *   const home = await sanityFetch(homePageQuery); // inferred as HomePageQueryResult
 *
 * Cache model (Next.js App Router):
 *   - `tags` → on-demand revalidation via `revalidateTag()`. When provided, `revalidate`
 *     is ignored (Next.js requires one or the other).
 *   - `revalidate` → time-based ISR. Defaults to 60 seconds. Pass `false` for no caching.
 */

type SanityFetchOptions = {
  params?: QueryParams;
  tags?: string[];
  revalidate?: number | false;
};

export async function sanityFetch<const Query extends string>(
  query: Query,
  { params, tags, revalidate = 60 }: SanityFetchOptions = {},
) {
  return sanityClient.fetch(query, params ?? {}, {
    next: {
      tags,
      revalidate: tags?.length ? false : revalidate,
    },
  });
}
